version: '3.3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: node_modules
        target: /app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    command: npm run dev

volumes:
  node_modules:
